[env]
MACOSX_DEPLOYMENT_TARGET = "10.14"

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "symbol-mangling-version=v0", "-C", "link-args=-Wl,-headerpad_max_install_names"]

[target.'cfg(not(target_os = "macos"))']
rustflags = ["-C", "symbol-mangling-version=v0"]

[net]
git-fetch-with-cli = true

[target.'cfg(target_family = "wasm")']
rustflags = ["--cfg=web_sys_unstable_apis"]
